[app]
env = "dev"
port = 8000
debug = true
secret = "3f4e25e75c08dbf60ad6533c50167ce3"

[db]
dsn = "postgres://postgres:woaini89xyq@101.35.6.67:5432/demo_rs"
options = { min_conns = 10, max_conns = 20, conn_timeout = 10, idle_timeout = 300, max_lifetime = 60 }

[redis]
dsn = "redis://101.35.6.67:6379/0"

[redis-cluster]
nodes = ["redis://101.35.6.67:6379/0"]

[log]
path = "logs"
filename = "tracing.log"
